exec(open("flow_probe.py").read().split('print("== A: EMO')[0])
import theme
print("== E: finger stays on B1 through its 10s sub ==")
w = make(); w._on_cta(); w._press_button("B1")
t = time.time()
for i in range(10): w._on_roi("B1", 2)
finish_sub_now(w); print(" after auto-advance:", S(w))
now = time.time()
w.fsm.update_vision("B1", now); w.fsm.update_vision("B1", now + 0.35); print(" finger still on B1 +0.35s:", S(w))
w.close()

print("== F: theme switch in IDLE — status rows stale ==")
w = make()
before = w.status_panel._rows[0].styleSheet()
w._on_theme_changed("light")
after = w.status_panel._rows[0].styleSheet()
print(" row0 qss unchanged after theme switch:", before == after, "|", after[:40])
theme.set_theme("dark"); w.close()

print("== G: scrim with sheet open while FSM flaps ==")
w = make(); w._on_cta(); w._toggle_menu(True); print(" menu open scrim:", not w.scrim.isHidden())
w._on_roi("B1", 2); w._on_roi("", 0)
for _ in range(3): w._on_roi("", 0)
time.sleep(0.4); w._on_roi("", 0)
print(" after hand in/out, menu still open:", not w.menu_panel.isHidden(), "scrim:", not w.scrim.isHidden())
w.close()

print("== H: gauge starts from previous full bar ==")
w = make(); w._on_cta(); w._press_button("B1"); finish_sub_now(w)
print(" gauge target after sub1:", w.gauge_panel._target_progress, "shown", w.gauge_panel._shown_progress)
w._press_button("B2"); print(" B2 sub start: shown progress", w.gauge_panel._shown_progress)
w.close()
